// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr6TOOQ6BWz2VRkPSlIwN5nCGh6_k6kyQ',
    appId: '1:18266098334:web:eb548abc72c4f40d71098f',
    messagingSenderId: '18266098334',
    projectId: 'shareyourjourney-5dcb0',
    authDomain: 'shareyourjourney-5dcb0.firebaseapp.com',
    storageBucket: 'shareyourjourney-5dcb0.appspot.com',
    measurementId: 'G-M9JW3Y7SRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvRyUwOaVMZUz8eemXaU3MHjp65udaEc',
    appId: '1:18266098334:android:9d5b2b8359c09cb371098f',
    messagingSenderId: '18266098334',
    projectId: 'shareyourjourney-5dcb0',
    storageBucket: 'shareyourjourney-5dcb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfC-CLs00N8_wSPO-4Eh8OhFiBsiYR2GI',
    appId: '1:18266098334:ios:19affaee9c2c315471098f',
    messagingSenderId: '18266098334',
    projectId: 'shareyourjourney-5dcb0',
    storageBucket: 'shareyourjourney-5dcb0.appspot.com',
    iosBundleId: 'com.ihsan.shareYourJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfC-CLs00N8_wSPO-4Eh8OhFiBsiYR2GI',
    appId: '1:18266098334:ios:9269b8695364e26771098f',
    messagingSenderId: '18266098334',
    projectId: 'shareyourjourney-5dcb0',
    storageBucket: 'shareyourjourney-5dcb0.appspot.com',
    iosBundleId: 'com.ihsan.shareYourJourney.RunnerTests',
  );
}
